"""initial migtareion

Revision ID: 2a2f4ea55398
Revises: 
Create Date: 2018-12-17 16:13:24.254453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a2f4ea55398'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.drop_column('roles', 'end_time')
    op.drop_column('roles', 'start_time')
    op.add_column('users', sa.Column('content', sa.String(length=200), nullable=True))
    op.drop_column('users', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('start_time', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'content')
    op.add_column('roles', sa.Column('start_time', mysql.DATETIME(), nullable=True))
    op.add_column('roles', sa.Column('end_time', mysql.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
